# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            rskpdev
tagline:          
description:      'Welcome to the website of <a href="https://github.com/rskpdev" target="_blank">Rahul Polisetti</a>.'
url:              rskpdev.github.io
baseurl:          /

author:
  name:           'Rahul Polisetti'
  url:            https://github.com/rskpdev

paginate:         3

# Custom vars
version:          1.0.0

github:           https://github.com/rskpdev

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist